spring:
  kafka:
    bootstrap-servers: kafka.local:9092
    #bootstrap-servers: ${KAFKA_BOOTSTRAP}:${KAFKA_BOOTSTRAP_PORT}
    template:
      default-topic: chat-topic
      #default-topic: ${KAFKA_TOPIC}
    consumer:
      group-id: chat-group
      #group-id: ${KAFKA_GROUP}
      auto-offset-reset: earliest
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
server:
  port: 8080
  #port: ${SERVER_PORT}
#logging:
#  level:
#    root: INFO
